Repository DeveloperAcademy-POSTECH/MacC-Team8-2HoSun, pull requests merged in 2023-11, with the labels that each got.

#89 학교 검색 등록 / 통합 검색 레이아웃
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Extensions/Color+.swift
  TwoHoSun/Model/DTO/SchoolResponseModel.swift
  TwoHoSun/Resources/Assets.xcassets/imgNoResult.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/imgNoResult.imageset/imgNoResult.svg
  TwoHoSun/Resources/Secret.plist
  TwoHoSun/Screens/Home/MainView/MainView.swift
  TwoHoSun/Screens/Home/MainView/SeachViewModel.swift
  TwoHoSun/Screens/Home/MainView/SearchView.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/Screens/ProfileSettings/SchoolSearchView.swift
  TwoHoSun/Screens/Search/SeachViewModel.swift
  TwoHoSun/Screens/Search/SearchView.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🐤 김

#90 온보딩 디자인 적용
  TwoHoSun/Extensions/Color+.swift
  TwoHoSun/Info.plist
  TwoHoSun/Resources/Assets.xcassets/launchScreenColor.colorset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/launchScreenLogo.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/launchScreenLogo.imageset/launchScreenLogo.svg
  TwoHoSun/Resources/Assets.xcassets/logo.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/logo.imageset/logo.svg
  TwoHoSun/Resources/Assets.xcassets/onboardingBackground.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/onboardingBackground.imageset/onboardingBackground 1.png
  TwoHoSun/Resources/Assets.xcassets/onboardingBackground.imageset/onboardingBackground 2.png
  TwoHoSun/Resources/Assets.xcassets/onboardingBackground.imageset/onboardingBackground.png
  TwoHoSun/Resources/Assets.xcassets/onboardingIllust.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/onboardingIllust.imageset/onboardingIllust.svg
  TwoHoSun/Resources/Assets.xcassets/splash.imageset/splash.svg
  TwoHoSun/Screens/Home/MainView/MainView.swift
  TwoHoSun/Screens/OnBoarding/BottomSheetView.swift
  TwoHoSun/Screens/OnBoarding/OnBoardingView.swift
Labels: feat, 🍪 남

#91 프로필등록하기 UI수정
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Extensions/Color+.swift
  TwoHoSun/Extensions/View+.swift
  TwoHoSun/Model/LoginModel/ProfileSetting.swift
  TwoHoSun/Network/APIManager.swift
  TwoHoSun/Resources/Assets.xcassets/defaultProfile.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/defaultProfile.imageset/_defaultProfile-1.svg
  TwoHoSun/Resources/Assets.xcassets/vote.imageset/Frame@1x.png
  TwoHoSun/Resources/Assets.xcassets/vote.imageset/Frame@2x.png
  TwoHoSun/Resources/Assets.xcassets/vote.imageset/Frame@3x.png
  TwoHoSun/Screens/Component/CustomConfirmModifier.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingViewModel.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
Labels: feat, 🎧 이

#94 알림 뷰 디자인 적용
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Extensions/Color+.swift
  TwoHoSun/Screens/Home/MainView/MainView.swift
  TwoHoSun/Screens/Home/MainView/NotificationView.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/Screens/ProfileSettings/SchoolSearchView.swift
  TwoHoSun/Screens/Search/SearchView.swift
Labels: feat, 🍪 남

#96 소비고민 탭 레이아웃 제작
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Extensions/Color+.swift
  TwoHoSun/Extensions/UIColor+.swift
  TwoHoSun/Resources/Assets.xcassets/icnCaretDown.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/icnCaretDown.imageset/icnCaretDown.svg
  TwoHoSun/Resources/Assets.xcassets/icnTabConsider.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/icnTabConsider.imageset/icnTabConsider.svg
  TwoHoSun/Resources/Assets.xcassets/icnTabConsiderSelected.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/icnTabConsiderSelected.imageset/Frame 1000001160.svg
  TwoHoSun/Resources/Assets.xcassets/icnTabMyPage.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/icnTabMyPage.imageset/icnTabMyPage.svg
  TwoHoSun/Resources/Assets.xcassets/icnTabMyPageSelected.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/icnTabMyPageSelected.imageset/person.crop.circle.svg
  TwoHoSun/Resources/Assets.xcassets/icnTabReview.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/icnTabReview.imageset/icnTabReview.svg
  TwoHoSun/Resources/Assets.xcassets/icnTabReviewSelected.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/icnTabReviewSelected.imageset/Frame 1000001161.svg
  TwoHoSun/Resources/Assets.xcassets/imgDefaultProfile.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/imgDefaultProfile.imageset/imgDefaultProfile.svg
  TwoHoSun/Screens/Common/WoteTabView.swift
  TwoHoSun/Screens/Home/Detail/ChartView.swift
  TwoHoSun/Screens/Home/Detail/ChartViewModel.swift
  TwoHoSun/Screens/Home/Detail/CommentCell.swift
  TwoHoSun/Screens/Home/Detail/DetailView.swift
  TwoHoSun/Screens/Home/Detail/DetailViewModel.swift
  TwoHoSun/Screens/Home/Main/ImageDetailView.swift
  TwoHoSun/Screens/Home/Main/LinkView.swift
  TwoHoSun/Screens/Home/Main/MainVoteView.swift
  TwoHoSun/Screens/Home/Main/MainVoteViewModel.swift
  TwoHoSun/Screens/Home/Main/VoteView.swift
  TwoHoSun/Screens/Home/MainTabView.swift
  TwoHoSun/Screens/Home/MainView/MainCellView.swift
  TwoHoSun/Screens/Home/MainView/MainViewModel.swift
  TwoHoSun/Screens/Home/Notification/NotificationView.swift
  TwoHoSun/Screens/Home/Search/SeachViewModel.swift
  TwoHoSun/Screens/Home/Search/SearchView.swift
  TwoHoSun/Screens/Home/Vote/VoteContentView.swift
  TwoHoSun/Screens/Home/Vote/VoteContentViewModel.swift
  TwoHoSun/Screens/OnBoarding/OnBoardingView.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🐤 김

#97 소비고민 탭 레이아웃 제작
  TwoHoSun/Screens/Common/WoteTabView.swift
  TwoHoSun/Screens/Home/Main/MainVoteView.swift
  TwoHoSun/Screens/Home/Search/SearchView.swift
Labels: feat, 🐤 김

#99 상세뷰 UI만들기
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Extensions/Color+.swift
  TwoHoSun/Model/EnumType/SpendTItleType.swift
  TwoHoSun/Resources/Assets.xcassets/smile.imageset/smile.svg
  TwoHoSun/Screens/Component/SpendTypeLabel.swift
  TwoHoSun/Screens/Home/Detail/ChartView.swift
  TwoHoSun/Screens/Home/Detail/ChartViewModel.swift
  TwoHoSun/Screens/Home/Detail/DetailView.swift
  TwoHoSun/Screens/Home/MainView/MainView.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🎧 이

#101 검색 레이아웃 제작
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Extensions/Color+.swift
  TwoHoSun/Extensions/UINavigationController+.swift
  TwoHoSun/Resources/Assets.xcassets/imgBuy.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/imgBuy.imageset/ImgBuy.svg
  TwoHoSun/Resources/Assets.xcassets/imgNotBuy.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/imgNotBuy.imageset/imgNotBuy.svg
  TwoHoSun/Screens/Component/SpendTypeLabel.swift
  TwoHoSun/Screens/Component/VoteCardView.swift
  TwoHoSun/Screens/Home/Main/MainVoteView.swift
  TwoHoSun/Screens/Home/Search/SeachViewModel.swift
  TwoHoSun/Screens/Home/Search/SearchView.swift
  TwoHoSun/Screens/ProfileSettings/SchoolSearchView.swift
  TwoHoSun/Screens/ProfileSettings/SchoolSearchViewModel.swift
  TwoHoSun/TwoHoSunApp.swift
  TwoHoSun/Utility/SearchTextFieldState.swift
Labels: feat, 🐤 김

#102 댓글 UI제작
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Extensions/Color+.swift
  TwoHoSun/Screens/Common/WoteTabView.swift
  TwoHoSun/Screens/Component/ExpandableTextView.swift
  TwoHoSun/Screens/Component/SpendTypeLabel.swift
  TwoHoSun/Screens/Component/VoteCardView.swift
  TwoHoSun/Screens/Home/Detail/CommentCell.swift
  TwoHoSun/Screens/Home/Detail/CommentsView.swift
  TwoHoSun/Screens/Home/Detail/DetailView.swift
  TwoHoSun/Screens/Home/Main/MainVoteView.swift
  TwoHoSun/Screens/Home/Search/SearchView.swift
  TwoHoSun/Screens/Modifiers/Keyboard.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/Screens/ProfileSettings/SchoolSearchView.swift
  TwoHoSun/Utility/SearchTextFieldState.swift
Labels: feat, 🎧 이

#104 투표 만들기 뷰 디자인 적용
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Screens/Component/CustomConfirmModifier.swift
  TwoHoSun/Screens/Home/Notification/NotificationView.swift
  TwoHoSun/Screens/Home/Write/WriteView.swift
  TwoHoSun/Screens/Home/Write/WriteViewModel.swift
  TwoHoSun/Screens/Modifiers/Keyboard.swift
Labels: feat, 🍪 남

#105 소비고민 탭 레이아웃 수정
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/AppDelegate.swift
  TwoHoSun/Model/EnumType/SpendTItleType.swift
  TwoHoSun/Model/FeedModel/CommentsModel.swift
  TwoHoSun/Resources/Assets.xcassets/imgNoVote.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/imgNoVote.imageset/Frame 1000001178@1x.png
  TwoHoSun/Resources/Assets.xcassets/imgNoVote.imageset/Frame 1000001178@2x.png
  TwoHoSun/Resources/Assets.xcassets/imgNoVote.imageset/Frame 1000001178@3x.png
  TwoHoSun/Screens/Common/WoteTabView.swift
  TwoHoSun/Screens/Component/ExpandableTextView.swift
  TwoHoSun/Screens/Home/Detail/CommentCell.swift
  TwoHoSun/Screens/Home/Detail/CommentsView.swift
  TwoHoSun/Screens/Home/Detail/DetailView.swift
  TwoHoSun/Screens/Home/Detail/DetailViewModel.swift
  TwoHoSun/Screens/Home/Main/ConsumptionConsiderationView.swift
  TwoHoSun/Screens/Home/Main/ConsumptionConsiderationViewModel.swift
  TwoHoSun/Screens/Home/Main/VoteView.swift
  TwoHoSun/Screens/Home/Write/WriteView.swift
  TwoHoSun/Screens/Home/Write/WriteViewModel.swift
Labels: feat, 🐤 김

#110 신고하기UI
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Extensions/Color+.swift
  TwoHoSun/Screens/Component/CustomAlertModalView.swift
  TwoHoSun/Screens/Component/CustomConfirmModifier.swift
  TwoHoSun/Screens/Component/ExpandableTextView.swift
  TwoHoSun/Screens/Home/Complaint/ComplaintReasonView.swift
  TwoHoSun/Screens/Home/Complaint/ComplaintView.swift
  TwoHoSun/Screens/Home/Detail/CommentCell.swift
  TwoHoSun/Screens/Home/Detail/CommentsView.swift
  TwoHoSun/Screens/Home/Detail/DetailView.swift
  TwoHoSun/Screens/Modifiers/Keyboard.swift
Labels: feat, 🎧 이

#108 후기 작성하기 레이아웃 제작
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Screens/Component/File
  TwoHoSun/Screens/Component/VoteCardView.swift
  TwoHoSun/Screens/Home/Main/ConsumptionConsiderationView.swift
  TwoHoSun/Screens/Home/Search/SearchView.swift
  TwoHoSun/Screens/Home/VoteWrite/VoteWriteView.swift
  TwoHoSun/Screens/Home/VoteWrite/VoteWriteViewModel.swift
  TwoHoSun/Screens/Review/ReviewWrite/ReviewWriteView.swift
  TwoHoSun/Screens/Review/ReviewWrite/ReviewWriteViewModel.swift
Labels: feat, 🍪 남

#115 상세뷰 UI수정
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Screens/Home/Detail/DetailView.swift
Labels: feat, 🎧 이

#122 Secret key 파일 오류 해결
  .gitignore
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Info.plist
  TwoHoSun/Resources/Secret.plist
  TwoHoSun/Resources/Secret.xcconfig
  TwoHoSun/Screens/ProfileSettings/SchoolSearchView.swift
  TwoHoSun/Screens/ProfileSettings/SchoolSearchViewModel.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: fix, 🐤 김

#123 마이페이지 레이아웃 제작
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Extensions/Color+.swift
  TwoHoSun/Resources/Assets.xcassets/imgWoteLogo.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/imgWoteLogo.imageset/imgWoteLogo.svg
  TwoHoSun/Resources/Secret.plist
  TwoHoSun/Screens/Common/NoReviewView.swift
  TwoHoSun/Screens/Common/NoVoteView.swift
  TwoHoSun/Screens/Common/WoteTabView.swift
  TwoHoSun/Screens/Component/GoToTypeTestButton.swift
  TwoHoSun/Screens/Component/ReviewCardCell.swift
  TwoHoSun/Screens/Component/VoteCardCell.swift
  TwoHoSun/Screens/Home/Main/ConsiderationView.swift
  TwoHoSun/Screens/MyPage/MyPageView.swift
  TwoHoSun/Screens/MyPage/SettingView.swift
  TwoHoSun/Screens/OnBoarding/OnBoardingView.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/Screens/Review/ReviewDetailView.swift
  TwoHoSun/Screens/Review/ReviewView.swift
  TwoHoSun/Screens/Review/ReviewWrite/Review/ReviewWrite/ReviewWriteView.swift
  TwoHoSun/Screens/Search/SearchView.swift
  TwoHoSun/Screens/TypeTest/TypeTestIntroView.swift
Labels: feat, 🐤 김

#128 모야모야 APImanager and error handling
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Extensions/String+.swift
  TwoHoSun/Model/DTO/PostResponseDto.swift
  TwoHoSun/Model/DTO/PostResponseModel.swift
  TwoHoSun/Model/FeedModel/Author.swift
  TwoHoSun/Model/FeedModel/PostModel.swift
  TwoHoSun/Model/LoginModel/ProfileSetting.swift
  TwoHoSun/Model/LoginModel/Tokens.swift
  TwoHoSun/Model/PostCreateModel.swift
  TwoHoSun/Network/APIManager.swift
  TwoHoSun/Network/Authenticator.swift
  TwoHoSun/Network/Foundation/APIConstants.swift
  TwoHoSun/Network/Foundation/ErrorResponse.swift
  TwoHoSun/Network/Foundation/GeneralResponse.swift
  TwoHoSun/Network/Foundation/MoyaPublisher.swift
  TwoHoSun/Network/Foundation/NetworkError.swift
  TwoHoSun/Network/Foundation/NetworkLoggerPlugin.swift
  TwoHoSun/Network/Manager/NewApiManager.swift
  TwoHoSun/Network/Service/CommentService.swift
  TwoHoSun/Network/Service/CommonAPIService.swift
  TwoHoSun/Network/Service/PostService.swift
  TwoHoSun/Network/Service/UserService.swift
  TwoHoSun/Screens/Common/WoteTabView.swift
  TwoHoSun/Screens/Component/CustomAlertModalView.swift
  TwoHoSun/Screens/Home/Complaint/ComplaintView.swift
  TwoHoSun/Screens/Home/Detail/CommentCell.swift
  TwoHoSun/Screens/Home/Detail/CommentsView.swift
  TwoHoSun/Screens/Home/Detail/DetailView.swift
  TwoHoSun/Screens/Home/Detail/DetailViewModel.swift
  TwoHoSun/Screens/Home/Main/ConsiderationView.swift
  TwoHoSun/Screens/Home/Main/ConsiderationViewModel.swift
  TwoHoSun/Screens/Home/Main/VoteContentCell.swift
  TwoHoSun/Screens/Home/Main/VoteView.swift
  TwoHoSun/Screens/Home/VoteWrite/VoteWriteViewModel.swift
  TwoHoSun/Screens/MyPage/MyPageView.swift
  TwoHoSun/Screens/OnBoarding/LoginViewModel.swift
  TwoHoSun/Screens/OnBoarding/OnBoardingView.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingViewModel.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/Screens/Review/ReviewView.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🎧 이

#127 설정 뷰 레이아웃 제작
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Extensions/Color+.swift
  TwoHoSun/Resources/Assets.xcassets/announcement.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/announcement.imageset/announcement.svg
  TwoHoSun/Screens/Component/CustomAlertModalView.swift
  TwoHoSun/Screens/Home/Main/LinkView.swift
  TwoHoSun/Screens/MyPage/Setting/SettingAnnouncementView.swift
  TwoHoSun/Screens/MyPage/Setting/SettingBlockView.swift
  TwoHoSun/Screens/MyPage/Setting/SettingNotificationView.swift
  TwoHoSun/Screens/MyPage/Setting/SettingQuestionsView.swift
  TwoHoSun/Screens/MyPage/Setting/SettingTermsView.swift
  TwoHoSun/Screens/MyPage/Setting/SettingView.swift
  TwoHoSun/Screens/MyPage/SettingView.swift
Labels: feat, 🍪 남

#133 투표 전체 조회 / 투표 상세 조회 api 연결
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Extensions/Color+.swift
  TwoHoSun/Extensions/Double+.swift
  TwoHoSun/Extensions/String+.swift
  TwoHoSun/Model/DTO/PostModel.swift
  TwoHoSun/Model/DTO/PostResponseDto.swift
  TwoHoSun/Model/EnumType/ConsumerType.swift
  TwoHoSun/Model/FeedModel/Author.swift
  TwoHoSun/Model/TypeTestModel.swift
  TwoHoSun/Network/Service/PostService.swift
  TwoHoSun/Resources/Assets.xcassets/icnReview.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/icnReview.imageset/icnReview.svg
  TwoHoSun/Resources/Assets.xcassets/imgDummyVote1.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/imgDummyVote1.imageset/imgDummyVote1.png
  TwoHoSun/Resources/Assets.xcassets/imgDummyVote2.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/imgDummyVote2.imageset/imgDummyVote2.png
  TwoHoSun/Resources/Assets.xcassets/imgDummyVote3.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/imgDummyVote3.imageset/imgDummyVote3.png
  TwoHoSun/Screens/Common/WoteTabView.swift
  TwoHoSun/Screens/Component/ConsumerTypeLabel.swift
  TwoHoSun/Screens/Component/CustomProgressStyle.swift
  TwoHoSun/Screens/Component/ImageView.swift
  TwoHoSun/Screens/Component/ProfileImageView.swift
  TwoHoSun/Screens/Component/ReviewCardCell.swift
  TwoHoSun/Screens/Component/VoteCardCell.swift
  TwoHoSun/Screens/Home/Detail/CommentCell.swift
  TwoHoSun/Screens/Home/Detail/DetailHeaderView.swift
  TwoHoSun/Screens/Home/Detail/DetailView.swift
  TwoHoSun/Screens/Home/Detail/DetailViewModel.swift
  TwoHoSun/Screens/Home/Main/ConsiderationView.swift
  TwoHoSun/Screens/Home/Main/ConsiderationViewModel.swift
  TwoHoSun/Screens/Home/Main/VoteContentCell.swift
  TwoHoSun/Screens/Home/Main/VoteView.swift
  TwoHoSun/Screens/Home/VoteWrite/VoteWriteView.swift
  TwoHoSun/Screens/Home/VoteWrite/VoteWriteViewModel.swift
  TwoHoSun/Screens/MyPage/MyPageView.swift
  TwoHoSun/Screens/OnBoarding/OnBoardingView.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/Screens/Review/ReviewDetailView.swift
  TwoHoSun/Screens/Review/ReviewView.swift
  TwoHoSun/Screens/Search/SearchView.swift
  TwoHoSun/Screens/TypeTest/TypeTestResultView.swift
  TwoHoSun/Screens/TypeTest/TypeTestView.swift
  TwoHoSun/Screens/TypeTest/TypeTestViewModel.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🐤 김

#139 소비성향결과 Put
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Model/LoginModel/Users.swift
  TwoHoSun/Network/Authenticator.swift
  TwoHoSun/Network/Foundation/NetworkLoggerPlugin.swift
  TwoHoSun/Network/Manager/NewApiManager.swift
  TwoHoSun/Network/Service/UserService.swift
  TwoHoSun/Screens/Common/WoteTabView.swift
  TwoHoSun/Screens/Home/Main/ConsiderationView.swift
  TwoHoSun/Screens/MyPage/MyPageView.swift
  TwoHoSun/Screens/OnBoarding/LoginViewModel.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/Screens/TypeTest/TypeTestView.swift
  TwoHoSun/Screens/TypeTest/TypeTestViewModel.swift
Labels: feat, 🎧 이

#141 마이페이지 나의 투표 API 연결
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Model/DTO/SummaryPostModel.swift
  TwoHoSun/Network/Service/PostService.swift
  TwoHoSun/Screens/Common/WoteTabView.swift
  TwoHoSun/Screens/Component/CardImageView.swift
  TwoHoSun/Screens/Component/VoteCardCell.swift
  TwoHoSun/Screens/MyPage/MyPageView.swift
  TwoHoSun/Screens/MyPage/MyPageViewModel.swift
  TwoHoSun/Screens/Review/ReviewDetailView.swift
  TwoHoSun/Screens/Review/ReviewWrite/Review/ReviewWrite/ReviewWriteView.swift
  TwoHoSun/Screens/Search/SearchView.swift
Labels: feat, 🍪 남

#145 게시글 투표하기 api
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Extensions/String+.swift
  TwoHoSun/Extensions/View+.swift
  TwoHoSun/Model/DTO/PostDetailModel.swift
  TwoHoSun/Model/DTO/PostModel.swift
  TwoHoSun/Model/DTO/ReviewTabModel.swift
  TwoHoSun/Model/DTO/SummaryPostModel.swift
  TwoHoSun/Model/DTO/VoteCreateRequestModel.swift
  TwoHoSun/Model/EnumType/PostEnums.swift
  TwoHoSun/Model/FeedModel/Author.swift
  TwoHoSun/Model/FeedModel/CommentsModel.swift
  TwoHoSun/Model/FeedModel/VoteCounts.swift
  TwoHoSun/Network/Manager/NewApiManager.swift
  TwoHoSun/Network/Service/PostService.swift
  TwoHoSun/Screens/Common/WoteTabView.swift
  TwoHoSun/Screens/Component/EndLabel.swift
  TwoHoSun/Screens/Component/InfoButton.swift
  TwoHoSun/Screens/Home/Detail/DetailHeaderView.swift
  TwoHoSun/Screens/Home/Detail/DetailView.swift
  TwoHoSun/Screens/Home/Detail/DetailViewModel.swift
  TwoHoSun/Screens/Home/Detail/LinkView.swift
  TwoHoSun/Screens/Home/Main/ConsiderationView.swift
  TwoHoSun/Screens/Home/Main/ConsiderationViewModel.swift
  TwoHoSun/Screens/Home/Main/ImageDetailView.swift
  TwoHoSun/Screens/Home/Main/VoteContentCell.swift
  TwoHoSun/Screens/Home/Main/VoteResultView.swift
  TwoHoSun/Screens/Home/Main/VoteView.swift
  TwoHoSun/Screens/Home/Main/VoteViewModel.swift
  TwoHoSun/Screens/Review/ReviewTabViewModel.swift
  TwoHoSun/Screens/Review/ReviewView.swift
  TwoHoSun/Utility/NavigationManager.swift
Labels: feat, 🐤 김

#148 투표 삭제 / 투표 즉시 종료 API 연결
  TwoHoSun/Extensions/View+.swift
  TwoHoSun/Network/Manager/NewApiManager.swift
  TwoHoSun/Network/Service/PostService.swift
  TwoHoSun/Screens/Component/CustomAlertModalView.swift
  TwoHoSun/Screens/Component/CustomConfirmModifier.swift
  TwoHoSun/Screens/Home/Detail/CommentsView.swift
  TwoHoSun/Screens/Home/Detail/DetailView.swift
  TwoHoSun/Screens/Home/Detail/DetailViewModel.swift
  TwoHoSun/Screens/Home/Main/VoteViewModel.swift
  TwoHoSun/Screens/Home/VoteWrite/VoteWriteView.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/Screens/Review/ReviewWrite/Review/ReviewWrite/ReviewWriteView.swift
  TwoHoSun/Utility/NavigationManager.swift
Labels: feat, 🐤 김

#149 댓글 CRUD
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Model/FeedModel/CommentPostModel.swift
  TwoHoSun/Model/FeedModel/CommentsModel.swift
  TwoHoSun/Network/Manager/NewApiManager.swift
  TwoHoSun/Network/Service/CommentService.swift
  TwoHoSun/Screens/Common/NoVoteView.swift
  TwoHoSun/Screens/Component/Comments/CommentCell.swift
  TwoHoSun/Screens/Component/Comments/CommentPreview.swift
  TwoHoSun/Screens/Component/Comments/CommentsView.swift
  TwoHoSun/Screens/Component/Comments/CommentsViewModel.swift
  TwoHoSun/Screens/Component/ConsumerTypeLabel.swift
  TwoHoSun/Screens/Home/Detail/CommentCell.swift
  TwoHoSun/Screens/Home/Detail/CommentsView.swift
  TwoHoSun/Screens/Home/Detail/DetailView.swift
  TwoHoSun/Screens/Home/Detail/DetailViewModel.swift
  TwoHoSun/Screens/Home/Main/ConsiderationView.swift
  TwoHoSun/Screens/Home/Main/VoteContentCell.swift
  TwoHoSun/Screens/MyPage/MyPageView.swift
  TwoHoSun/Screens/OnBoarding/OnBoardingView.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/Screens/Review/ReviewDetailView.swift
Labels: feat, 🎧 이

#151 마이페이지 나의 후기 API 연결
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Model/DTO/SummaryPostModel.swift
  TwoHoSun/Network/Service/PostService.swift
  TwoHoSun/Screens/Component/ReviewCardCell.swift
  TwoHoSun/Screens/Component/VoteCardCell.swift
  TwoHoSun/Screens/MyPage/MyPageView.swift
  TwoHoSun/Screens/MyPage/MyPageViewModel.swift
  TwoHoSun/Screens/Review/ReviewView.swift
  TwoHoSun/Screens/Search/SearchView.swift
Labels: feat, 🍪 남

#154 마이페이지 프로필 API 연결
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Extensions/Color+.swift
  TwoHoSun/Model/EnumType/ConsumerType.swift
  TwoHoSun/Model/LoginModel/ProfileSetting.swift
  TwoHoSun/Model/LoginModel/SchoolModel.swift
  TwoHoSun/Model/PostDetailModel.swift
  TwoHoSun/Model/PostModel.swift
  TwoHoSun/Model/ProfileModel.swift
  TwoHoSun/Model/ReviewTabModel.swift
  TwoHoSun/Model/SchoolResponseModel.swift
  TwoHoSun/Model/SummaryPostModel.swift
  TwoHoSun/Model/VoteCreateRequestModel.swift
  TwoHoSun/Network/Service/UserService.swift
  TwoHoSun/Screens/MyPage/MyPageView.swift
  TwoHoSun/Screens/MyPage/MyPageViewModel.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingViewModel.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/Screens/ProfileSettings/SchoolSearchView.swift
  TwoHoSun/Screens/Review/ReviewTabViewModel.swift
Labels: feat, 🍪 남

#136 Notification 기초 공사
  TwoHoSun/AppDelegate.swift
  TwoHoSun/Info.plist
Labels: feat

#156 검색연결작업
  TwoHoSun/Model/EnumType/PostEnums.swift
  TwoHoSun/Model/PostDetailModel.swift
  TwoHoSun/Model/SummaryPostModel.swift
  TwoHoSun/Network/Service/PostService.swift
  TwoHoSun/Screens/Common/WoteTabView.swift
  TwoHoSun/Screens/Component/Comments/CommentCell.swift
  TwoHoSun/Screens/Component/VoteCardCell.swift
  TwoHoSun/Screens/Home/Detail/DetailView.swift
  TwoHoSun/Screens/Home/Main/ConsiderationView.swift
  TwoHoSun/Screens/Home/Main/VoteViewModel.swift
  TwoHoSun/Screens/MyPage/MyPageView.swift
  TwoHoSun/Screens/Search/SeachViewModel.swift
  TwoHoSun/Screens/Search/SearchView.swift
Labels: feat, 🎧 이

#159 notification연결작업
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/AppDelegate.swift
  TwoHoSun/Network/Authenticator.swift
  TwoHoSun/Network/Foundation/APIConstants.swift
  TwoHoSun/Network/Service/PostService.swift
  TwoHoSun/Network/Service/UserService.swift
  TwoHoSun/Screens/Common/NoVoteView.swift
  TwoHoSun/Screens/Common/WoteTabView.swift
  TwoHoSun/Screens/Component/GoToTypeTestButton.swift
  TwoHoSun/Screens/Home/Detail/DetailView.swift
  TwoHoSun/Screens/Home/Main/ConsiderationView.swift
  TwoHoSun/Screens/Home/Notification/NotificationModel.swift
  TwoHoSun/Screens/Home/Notification/NotificationView.swift
  TwoHoSun/Screens/MyPage/MyPageView.swift
  TwoHoSun/Screens/ProfileSettings/SchoolSearchView.swift
  TwoHoSun/Screens/TypeTest/TypeTestIntroView.swift
  TwoHoSun/Screens/TypeTest/TypeTestResultView.swift
  TwoHoSun/Screens/TypeTest/TypeTestView.swift
  TwoHoSun/TwoHoSunApp.swift
  TwoHoSun/Utility/KeychainManager.swift
  TwoHoSun/Utility/NavigationManager.swift
Labels: feat, 🎧 이

#158 후기 작성하기 API 연결
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Model/ReviewCreateModel.swift
  TwoHoSun/Network/Service/PostService.swift
  TwoHoSun/Screens/Common/NoReviewView.swift
  TwoHoSun/Screens/Component/ImageCropView.swift
  TwoHoSun/Screens/Component/VoteCardCell.swift
  TwoHoSun/Screens/Home/Detail/DetailHeaderView.swift
  TwoHoSun/Screens/Home/VoteWrite/VoteWriteView.swift
  TwoHoSun/Screens/MyPage/MyPageView.swift
  TwoHoSun/Screens/Review/ReviewWrite/Review/ReviewWrite/ReviewWriteView.swift
  TwoHoSun/Screens/Review/ReviewWrite/Review/ReviewWrite/ReviewWriteViewModel.swift
Labels: feat, 🍪 남

#162 버그들 fix
  TwoHoSun/Extensions/View+.swift
  TwoHoSun/Network/Authenticator.swift
  TwoHoSun/Screens/Common/WoteTabView.swift
  TwoHoSun/Screens/Home/Detail/DetailView.swift
  TwoHoSun/Screens/OnBoarding/BottomSheetView.swift
  TwoHoSun/Screens/OnBoarding/LoginViewModel.swift
  TwoHoSun/Screens/OnBoarding/OnBoardingView.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/Screens/Review/ReviewDetailView.swift
  TwoHoSun/Screens/Review/ReviewView.swift
  TwoHoSun/Screens/Search/SearchView.swift
  TwoHoSun/TwoHoSunApp.swift
  TwoHoSun/Utility/KeychainManager.swift
  TwoHoSun/Utility/NavigationManager.swift
Labels: fix, 🎧 이

#163 회원 탈퇴 API 연결 및 로그아웃 구현
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Network/Service/UserService.swift
  TwoHoSun/Screens/Common/WoteTabView.swift
  TwoHoSun/Screens/MyPage/Setting/SettingTermsView.swift
  TwoHoSun/Screens/MyPage/Setting/SettingView.swift
  TwoHoSun/Screens/MyPage/Setting/SettingViewModel.swift
  TwoHoSun/Screens/OnBoarding/OnBoardingView.swift
Labels: feat, 🍪 남

#165 소비 후기 탭 조회 / 뷰 연결
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun.xcodeproj/xcshareddata/xcschemes/TwoHoSun.xcscheme
  TwoHoSun/Model/EnumType/PostEnums.swift
  TwoHoSun/Model/PostModel.swift
  TwoHoSun/Model/ReviewDetailModel.swift
  TwoHoSun/Model/ReviewTabModel.swift
  TwoHoSun/Model/SummaryPostModel.swift
  TwoHoSun/Network/Service/PostService.swift
  TwoHoSun/Resources/Assets.xcassets/icnDummyLogo.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/icnDummyLogo.imageset/icnDummyLogo.svg
  TwoHoSun/Screens/Common/WoteTabView.swift
  TwoHoSun/Screens/Component/CardImageView.swift
  TwoHoSun/Screens/Component/CustomAlertModalView.swift
  TwoHoSun/Screens/Component/ImageView.swift
  TwoHoSun/Screens/Component/ReviewCardCell.swift
  TwoHoSun/Screens/Component/VoteCardCell.swift
  TwoHoSun/Screens/Home/Detail/DetailHeaderView.swift
  TwoHoSun/Screens/Home/Detail/DetailView.swift
  TwoHoSun/Screens/Home/Detail/DetailViewModel.swift
  TwoHoSun/Screens/Home/Main/ConsiderationView.swift
  TwoHoSun/Screens/Home/Main/ConsiderationViewModel.swift
  TwoHoSun/Screens/Home/Main/VoteContentCell.swift
  TwoHoSun/Screens/Home/Main/VoteViewModel.swift
  TwoHoSun/Screens/MyPage/MyPageView.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/Screens/Review/ReviewDetailView.swift
  TwoHoSun/Screens/Review/ReviewDetailViewModel.swift
  TwoHoSun/Screens/Review/ReviewTabViewModel.swift
  TwoHoSun/Screens/Review/ReviewView.swift
  TwoHoSun/Screens/Review/TestViewModel.swift
  TwoHoSun/Screens/Search/SearchView.swift
  TwoHoSun/TwoHoSunApp.swift
  TwoHoSun/Utility/NavigationManager.swift
Labels: feat, 🐤 김

#168 후기 작성 뷰 이미지 다시 선택 시 이전 이미지가 업로드 되는 버그 수정
  TwoHoSun/Screens/Review/ReviewWrite/Review/ReviewWrite/ReviewWriteView.swift
Labels: fix, 🍪 남

#171 모든 뷰에서 사용 가능하도록 프로필 이미지 패치 통합
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Network/Manager/MemberManager.swift
  TwoHoSun/Screens/Component/Comments/CommentCell.swift
  TwoHoSun/Screens/Component/Comments/CommentPreview.swift
  TwoHoSun/Screens/Component/Comments/CommentsView.swift
  TwoHoSun/Screens/MyPage/MyPageView.swift
  TwoHoSun/Screens/MyPage/MyPageViewModel.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🍪 남

#173 remote 노티작업
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/AppDelegate.swift
  TwoHoSun/Extensions/Date+.swift
  TwoHoSun/Model/FeedModel/CommentPostModel.swift
  TwoHoSun/Model/LoginModel/Users.swift
  TwoHoSun/Network/Manager/NewApiManager.swift
  TwoHoSun/Network/Service/UserService.swift
  TwoHoSun/Screens/Common/WoteTabView.swift
  TwoHoSun/Screens/Component/Comments/CommentCell.swift
  TwoHoSun/Screens/Component/Comments/CommentPreview.swift
  TwoHoSun/Screens/Component/Comments/CommentsView.swift
  TwoHoSun/Screens/Component/VoteCardCell.swift
  TwoHoSun/Screens/Home/Detail/DetailView.swift
  TwoHoSun/Screens/Home/Notification/DataController.swift
  TwoHoSun/Screens/Home/Notification/DataModel.xcdatamodeld/Model.xcdatamodel/contents
  TwoHoSun/Screens/Home/Notification/NotiDecodeModel.swift
  TwoHoSun/Screens/Home/Notification/NotificationModel.swift
  TwoHoSun/Screens/Home/Notification/NotificationView.swift
  TwoHoSun/Screens/MyPage/Setting/SettingViewModel.swift
  TwoHoSun/Screens/OnBoarding/BottomSheetView.swift
  TwoHoSun/Screens/OnBoarding/LoginViewModel.swift
  TwoHoSun/Screens/OnBoarding/OnBoardingView.swift
  TwoHoSun/Screens/Review/ReviewDetailView.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🎧 이

#174 후기 삭제 시 소비 후기 탭 목록 관리 / 후기 작성 API 뷰 연결
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Extensions/NSNotification+.swift
  TwoHoSun/Model/EnumType/PostEnums.swift
  TwoHoSun/Model/PostDetailModel.swift
  TwoHoSun/Model/PostModel.swift
  TwoHoSun/Model/ReviewTabModel.swift
  TwoHoSun/Model/SummaryPostModel.swift
  TwoHoSun/Network/Service/PostService.swift
  TwoHoSun/Screens/Common/WoteTabView.swift
  TwoHoSun/Screens/Component/ReviewCardCell.swift
  TwoHoSun/Screens/Component/VoteCardCell.swift
  TwoHoSun/Screens/Home/Detail/DetailHeaderView.swift
  TwoHoSun/Screens/Home/Detail/DetailHeaderViewModel.swift
  TwoHoSun/Screens/Home/Detail/DetailView.swift
  TwoHoSun/Screens/Home/Detail/DetailViewModel.swift
  TwoHoSun/Screens/Home/Main/ConsiderationView.swift
  TwoHoSun/Screens/Home/Main/ConsiderationViewModel.swift
  TwoHoSun/Screens/Home/Main/VoteContentCell.swift
  TwoHoSun/Screens/Home/Notification/NotificationView.swift
  TwoHoSun/Screens/Home/VoteWrite/VoteWriteView.swift
  TwoHoSun/Screens/Home/VoteWrite/VoteWriteViewModel.swift
  TwoHoSun/Screens/MyPage/MyPageView.swift
  TwoHoSun/Screens/MyPage/MyPageViewModel.swift
  TwoHoSun/Screens/Review/ReviewDetailView.swift
  TwoHoSun/Screens/Review/ReviewDetailViewModel.swift
  TwoHoSun/Screens/Review/ReviewTabViewModel.swift
  TwoHoSun/Screens/Review/ReviewView.swift
  TwoHoSun/Screens/Review/ReviewWrite/Review/ReviewWrite/ReviewWriteView.swift
  TwoHoSun/Screens/Review/ReviewWrite/Review/ReviewWrite/ReviewWriteViewModel.swift
  TwoHoSun/Screens/Search/SearchView.swift
  TwoHoSun/Screens/TypeTest/TypeTestView.swift
  TwoHoSun/TwoHoSunApp.swift
  TwoHoSun/Utility/NavigationManager.swift
  TwoHoSun/Utility/PostManager.swift
  TwoHoSun/Utility/ReviewManager.swift
Labels: feat, 🐤 김

#175 사용자 차단 API 연결
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Model/BlockUserModel.swift
  TwoHoSun/Network/Manager/MemberManager.swift
  TwoHoSun/Network/Service/UserService.swift
  TwoHoSun/Screens/Component/Comments/CommentsView.swift
  TwoHoSun/Screens/Home/Detail/DetailView.swift
  TwoHoSun/Screens/MyPage/Setting/SettingBlockView.swift
  TwoHoSun/Screens/MyPage/Setting/SettingView.swift
  TwoHoSun/Screens/MyPage/Setting/SettingViewModel.swift
  TwoHoSun/Screens/Review/ReviewDetailView.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🍪 남

#183 댓글 버그 픽스
  TwoHoSun/Extensions/Color+.swift
  TwoHoSun/Model/EnumType/ConsumerType.swift
  TwoHoSun/Model/FeedModel/CommentsModel.swift
  TwoHoSun/Model/PostDetailModel.swift
  TwoHoSun/Model/PostModel.swift
  TwoHoSun/Model/ReviewDetailModel.swift
  TwoHoSun/Network/Authenticator.swift
  TwoHoSun/Resources/Assets.xcassets/icnBan.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/icnBan.imageset/ban-svgrepo-com 1.svg
  TwoHoSun/Screens/Component/Comments/CommentCell.swift
  TwoHoSun/Screens/Component/Comments/CommentPreview.swift
  TwoHoSun/Screens/Component/Comments/CommentsView.swift
  TwoHoSun/Screens/Component/ProfileImageView.swift
  TwoHoSun/Screens/Home/Detail/DetailView.swift
  TwoHoSun/Screens/Review/ReviewDetailView.swift
  TwoHoSun/Screens/Review/ReviewDetailViewModel.swift
Labels: fix, 🎧 이

#185 프로필 세팅 뷰 버그 Fix
  TwoHoSun/Network/Service/UserService.swift
  TwoHoSun/Screens/Common/WoteTabView.swift
  TwoHoSun/Screens/MyPage/MyPageView.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingViewModel.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/Utility/NavigationManager.swift
Labels: fix, 🍪 남

#188 회원가입 시 마이페이지 프로필이 나타나지 않는 버그
  TwoHoSun/Model/ProfileModel.swift
  TwoHoSun/Screens/MyPage/MyPageView.swift
Labels: fix, 🍪 남

#189 버그 fix
  TwoHoSun/Extensions/NSNotification+.swift
  TwoHoSun/Model/ReviewTabModel.swift
  TwoHoSun/Network/Manager/MemberManager.swift
  TwoHoSun/Screens/Common/WoteTabView.swift
  TwoHoSun/Screens/Home/Main/ConsiderationView.swift
  TwoHoSun/Screens/Home/Main/ConsiderationViewModel.swift
  TwoHoSun/Screens/MyPage/Setting/SettingViewModel.swift
  TwoHoSun/Screens/OnBoarding/BottomSheetView.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/Screens/Review/ReviewView.swift
  TwoHoSun/Utility/ReviewManager.swift
  TwoHoSun/Utility/TermAgreeType.swift
Labels: feat, 🐤 김
