Repository DeveloperAcademy-POSTECH/MacC-Team8-2HoSun, pull requests merged in 2023-10, with the labels that each got.

#4 로그인 토큰 관리
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Screens/KeychainManager.swift
Labels: feat, 🍪 남

#5 애플로그인 토큰 요청
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/.swiftlint.yml
  TwoHoSun/Screens/Login/LoginModel.swift
  TwoHoSun/Screens/Login/LoginView.swift
  TwoHoSun/Screens/Login/LoginViewModel.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🎧 이

#8 프로필설정뷰 레이아웃 그리기 및 기능 추가
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/.swiftlint.yml
  TwoHoSun/Screens/KeychainManager.swift
  TwoHoSun/Screens/Login/LoginModel.swift
  TwoHoSun/Screens/Login/LoginView.swift
  TwoHoSun/Screens/Login/LoginViewModel.swift
  TwoHoSun/Screens/ProfileSettings/View/ProfileSettingsView.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🐤 김

#10 앱 실행 시 토큰 관리 및 검증
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Info.plist
  TwoHoSun/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/splash.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/splash.imageset/splash.svg
  TwoHoSun/Screens/Home/HomeView.swift
  TwoHoSun/Screens/Login/LoginView.swift
  TwoHoSun/Screens/Login/LoginViewModel.swift
  TwoHoSun/TwoHoSunApp.swift
  TwoHoSun/Utility/KeychainManager.swift
Labels: feat, 🍪 남

#12 프로필설정뷰 레이아웃 그리기 및 기능 추가
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Screens/ProfileSettings/View/ProfileSettingsView.swift
Labels: feat, 🐤 김

#14 충돌로 인한 온보딩페이지 머지 작업
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Screens/Login/LoginView.swift
  TwoHoSun/Screens/OnBoarding/BottomSheetView.swift
  TwoHoSun/Screens/OnBoarding/DesciptionView.swift
  TwoHoSun/Screens/OnBoarding/LoginViewModel.swift
  TwoHoSun/Screens/OnBoarding/OnBoardingView.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: fix, 🎧 이

#17 학교 검색 및 등록 기능 개발
  .gitignore
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Info.plist
  TwoHoSun/Model/SchoolModel.swift
  TwoHoSun/Model/SchoolResponseModel.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/Screens/ProfileSettings/SchoolSearchView.swift
  TwoHoSun/Screens/ProfileSettings/SchoolSearchViewModel.swift
Labels: feat, 🐤 김

#21 학교 정보 API Key 저장
  .gitignore
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Resources/Secret.plist
  TwoHoSun/Screens/ProfileSettings/SchoolSearchViewModel.swift
Labels: feat, 🐤 김

#23 학교 검색 레이아웃 제작 및 검색 기능 연결
  TwoHoSun/Model/SchoolModel.swift
  TwoHoSun/Model/SchoolResponseModel.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/Screens/ProfileSettings/SchoolSearchView.swift
  TwoHoSun/Screens/ProfileSettings/SchoolSearchViewModel.swift
Labels: feat, 🐤 김

#25 로그인할때 회원정보 있는지 체크
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Model/GeneralResponse.swift
  TwoHoSun/Model/LoginModel.swift
  TwoHoSun/Screens/Home/HomeView.swift
  TwoHoSun/Screens/OnBoarding/BottomSheetView.swift
  TwoHoSun/Screens/OnBoarding/LoginViewModel.swift
  TwoHoSun/Screens/OnBoarding/OnBoardingView.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🎧 이

#26 닉네임 중복확인 API 통신
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/.swiftlint.yml
  TwoHoSun/Model/NicknameModel.swift
  TwoHoSun/Screens/ContentView/ContentView.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingViewModel.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🍪 남

#27 feat(profileSettings): add API logic for profile setting post
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Model/GeneralResponse.swift
  TwoHoSun/Model/ProfileSettingModel.swift
  TwoHoSun/Model/SchoolModel.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingViewModel.swift
Labels: feat, 🍪 남

#30 프로필 설정 정보 유효성 검사 및 데이터 연결
  TwoHoSun/Screens/OnBoarding/OnBoardingView.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingViewModel.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🐤 김

#32 메인뷰 셀 제외하고 틀 만들기
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Screens/Home/HomeView.swift
  TwoHoSun/Screens/Home/MainTabView.swift
  TwoHoSun/Screens/Home/MainView/MainView.swift
  TwoHoSun/Screens/Home/MainView/MainViewModel.swift
  TwoHoSun/Screens/Home/WriteView.swift
  TwoHoSun/Screens/OnBoarding/BottomSheetView.swift
  TwoHoSun/Screens/OnBoarding/LoginViewModel.swift
  TwoHoSun/Screens/OnBoarding/OnBoardingView.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🎧 이

#37 상세뷰 페이지 제작
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/.swiftlint.yml
  TwoHoSun/Extensions/View+.swift
  TwoHoSun/Resources/Assets.xcassets/smile.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/smile.imageset/smile.svg
  TwoHoSun/Screens/Home/DetailView/CommentCell.swift
  TwoHoSun/Screens/Home/DetailView/DetailView.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🎧 이

#39 메인뷰 투표 셀 레이아웃 및 투표글 모델 구성
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Model/DTO/PostResponseModel.swift
  TwoHoSun/Model/DTO/SchoolResponseModel.swift
  TwoHoSun/Model/PostModel.swift
  TwoHoSun/Screens/Home/Vote/ImageDetailView.swift
  TwoHoSun/Screens/Home/Vote/VoteCellView.swift
  TwoHoSun/Screens/Home/Vote/VoteContentView.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🐤 김

#41 링크 버튼 눌렀을 때 해당 링크 웹뷰 띄우기
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Screens/Home/Vote/ImageDetailView.swift
  TwoHoSun/Screens/Home/Vote/LinkView.swift
  TwoHoSun/Screens/Home/Vote/VoteContentView.swift
Labels: feat, 🐤 김

#44 앱 내 모든 API 통신을 위한 통합 API Manager
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Network/APIManager.swift
  TwoHoSun/Screens/OnBoarding/LoginViewModel.swift
  TwoHoSun/Screens/OnBoarding/OnBoardingView.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingViewModel.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🍪 남

#49 APIManager 헤더 수정 및 파라미터 추가
  TwoHoSun/Network/APIManager.swift
  TwoHoSun/Screens/OnBoarding/LoginViewModel.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingViewModel.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: fix, 🍪 남

#50 게시글 투표 api 통신
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Model/DTO/VoteCreateRequestModel.swift
  TwoHoSun/Network/APIManager.swift
  TwoHoSun/Screens/Home/Vote/VoteContentView.swift
  TwoHoSun/Screens/Home/Vote/VoteContentViewModel.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🐤 김

#51 소비고민 등록뷰 레이아웃 제작
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Screens/Home/MainView/MainView.swift
  TwoHoSun/Screens/Home/Write/WriteView.swift
  TwoHoSun/Screens/Home/Write/WriteViewModel.swift
  TwoHoSun/Screens/Home/WriteView.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🐤 김

#56 메인뷰 연결
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Model/DTO/PostResponseModel.swift
  TwoHoSun/Model/PostModel.swift
  TwoHoSun/Network/APIManager.swift
  TwoHoSun/Screens/Home/DetailView/CommentCell.swift
  TwoHoSun/Screens/Home/DetailView/DetailView.swift
  TwoHoSun/Screens/Home/MainView/MainCellView.swift
  TwoHoSun/Screens/Home/MainView/MainView.swift
  TwoHoSun/Screens/Home/MainView/MainViewModel.swift
  TwoHoSun/Screens/Home/Vote/VoteCellView.swift
  TwoHoSun/Screens/Home/Vote/VoteContentView.swift
  TwoHoSun/Screens/Home/Vote/VoteContentViewModel.swift
  TwoHoSun/Screens/OnBoarding/BottomSheetView.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingViewModel.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🎧 이

#58 프로필세팅뷰 지역 데이터 형식 변경
  TwoHoSun/Model/DTO/SchoolResponseModel.swift
  TwoHoSun/Screens/Home/MainView/SearchView.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🐤 김

#62 댓글 CRUD
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Extensions/Date+.swift
  TwoHoSun/Extensions/String+.swift
  TwoHoSun/Model/CommonModel/CommonModel.swift
  TwoHoSun/Model/DTO/GeneralResponse.swift
  TwoHoSun/Model/DTO/PostResponseModel.swift
  TwoHoSun/Model/FeedModel/Author.swift
  TwoHoSun/Model/FeedModel/CommentPostModel.swift
  TwoHoSun/Model/FeedModel/CommentsModel.swift
  TwoHoSun/Model/FeedModel/PostModel.swift
  TwoHoSun/Model/FeedModel/VoteCounts.swift
  TwoHoSun/Model/LoginModel/NicknameValidation.swift
  TwoHoSun/Model/LoginModel/ProfileSetting.swift
  TwoHoSun/Model/LoginModel/SchoolModel.swift
  TwoHoSun/Model/LoginModel/Tokens.swift
  TwoHoSun/Model/PostCreateModel.swift
  TwoHoSun/Network/APIManager.swift
  TwoHoSun/Resources/Secret.plist
  TwoHoSun/Screens/Home/DetailView/CommentCell.swift
  TwoHoSun/Screens/Home/DetailView/DetailView.swift
  TwoHoSun/Screens/Home/DetailView/DetailViewModel.swift
  TwoHoSun/Screens/Home/MainTabView.swift
  TwoHoSun/Screens/Home/MainView/MainView.swift
  TwoHoSun/Screens/Home/MainView/MainViewModel.swift
  TwoHoSun/Screens/Home/MainView/SearchView.swift
  TwoHoSun/Screens/Home/Vote/VoteContentView.swift
  TwoHoSun/Screens/Home/Write/WriteView.swift
  TwoHoSun/Screens/Home/Write/WriteViewModel.swift
  TwoHoSun/Screens/OnBoarding/LoginViewModel.swift
  TwoHoSun/Screens/OnBoarding/OnBoardingView.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingViewModel.swift
  TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
  TwoHoSun/TwoHoSunApp.swift
  TwoHoSun/Utility/KeychainManager.swift
Labels: feat, 🎧 이

#60 학교 검색 레이아웃 수정사항 반영
  TwoHoSun/Screens/ProfileSettings/SchoolSearchView.swift
Labels: feat, 🐤 김

#65 뷰연결
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Model/FeedModel/CommentsModel.swift
  TwoHoSun/Screens/Home/DetailView/DetailView.swift
  TwoHoSun/Screens/Home/MainView/MainView.swift
  TwoHoSun/Screens/Home/Vote/VoteContentView.swift
  TwoHoSun/Screens/Home/Write/WriteViewModel.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: fix, feat, 🎧 이

#69 통합검색 api 통신 및 뷰 수정사항 반영
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Model/DTO/PostResponseModel.swift
  TwoHoSun/Network/APIManager.swift
  TwoHoSun/Screens/Home/MainView/MainView.swift
  TwoHoSun/Screens/Home/MainView/SeachViewModel.swift
  TwoHoSun/Screens/Home/MainView/SearchView.swift
  TwoHoSun/Screens/Home/Write/WriteView.swift
Labels: feat, 🐤 김

#68 본인 투표에 대한 상세보기 뷰
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Model/ChartModel.swift
  TwoHoSun/Model/DTO/PostResponseModel.swift
  TwoHoSun/Model/DTO/SchoolResponseModel.swift
  TwoHoSun/Model/LoginModel/SchoolModel.swift
  TwoHoSun/Model/PostCreateModel.swift
  TwoHoSun/Model/VoteInfoModel.swift
  TwoHoSun/Network/APIManager.swift
  TwoHoSun/Screens/Home/DetailView/ChartView.swift
  TwoHoSun/Screens/Home/DetailView/ChartViewModel.swift
  TwoHoSun/Screens/Home/DetailView/MyDetailView.swift
  TwoHoSun/Screens/Home/DetailView/OthersDetailView.swift
  TwoHoSun/Screens/Home/Vote/VoteCellView.swift
  TwoHoSun/Screens/Home/Vote/VoteContentView.swift
  TwoHoSun/Screens/ProfileSettings/SchoolSearchView.swift
  TwoHoSun/Screens/ProfileSettings/SchoolSearchViewModel.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat, 🍪 남

#71 온보딩뷰 수정
  TwoHoSun/Resources/Assets.xcassets/dummyImg.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/dummyImg.imageset/Vector@1x.png
  TwoHoSun/Resources/Assets.xcassets/dummyImg.imageset/Vector@2x.png
  TwoHoSun/Resources/Assets.xcassets/dummyImg.imageset/Vector@3x.png
  TwoHoSun/Resources/Assets.xcassets/vote.imageset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/vote.imageset/Frame@1x.png
  TwoHoSun/Resources/Assets.xcassets/vote.imageset/Frame@2x.png
  TwoHoSun/Resources/Assets.xcassets/vote.imageset/Frame@3x.png
  TwoHoSun/Screens/OnBoarding/OnBoardingView.swift
Labels: feat, 🐤 김

#72 검색 뷰 버그 수정
  TwoHoSun/Screens/Home/MainView/NotificationView.swift
  TwoHoSun/Screens/Home/MainView/SeachViewModel.swift
  TwoHoSun/Screens/Home/MainView/SearchView.swift
Labels: fix, 🍪 남

#73 게시글 상세 조회 api 통신
  TwoHoSun/Model/DTO/PostResponseModel.swift
  TwoHoSun/Model/DTO/VoteCreateRequestModel.swift
  TwoHoSun/Model/FeedModel/PostModel.swift
  TwoHoSun/Model/PostCreateModel.swift
  TwoHoSun/Network/APIManager.swift
  TwoHoSun/Screens/Home/DetailView/DetailViewModel.swift
  TwoHoSun/Screens/Home/DetailView/OthersDetailView.swift
  TwoHoSun/Screens/Home/Vote/VoteContentView.swift
  TwoHoSun/Screens/Home/Write/WriteViewModel.swift
Labels: feat, 🐤 김

#75 Invalid frame dimension 오류 해결
  TwoHoSun/Screens/Home/DetailView/ChartView.swift
Labels: fix, 🍪 남

#77 차트 뷰 API 통신 및 상위 뷰 연결
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Model/DTO/PostResponseModel.swift
  TwoHoSun/Model/FeedModel/PostModel.swift
  TwoHoSun/Screens/Home/DetailView/ChartView.swift
  TwoHoSun/Screens/Home/DetailView/ChartViewModel.swift
  TwoHoSun/Screens/Home/DetailView/DetailView.swift
  TwoHoSun/Screens/Home/DetailView/MyDetailView.swift
  TwoHoSun/Screens/Home/Vote/VoteContentView.swift
Labels: feat, 🍪 남

#79 버그 수정 및 UI 수정
  TwoHoSun/Model/DTO/VoteCreateRequestModel.swift
  TwoHoSun/Network/APIManager.swift
  TwoHoSun/Resources/Assets.xcassets/agreeColor.colorset/Contents.json
  TwoHoSun/Resources/Assets.xcassets/disagreeColor.colorset/Contents.json
  TwoHoSun/Screens/Home/Vote/VoteContentView.swift
  TwoHoSun/Screens/Home/Vote/VoteContentViewModel.swift
  TwoHoSun/Screens/Home/Write/WriteViewModel.swift
Labels: feat, 🐤 김

#82 Push notification를 위한 AppDelegate 추가
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/AppDelegate.swift
  TwoHoSun/TwoHoSunApp.swift
Labels: feat

#84 색상정리
  TwoHoSun.xcodeproj/project.pbxproj
  TwoHoSun/Extensions/Color+.swift
  TwoHoSun/Extensions/UIColor+.swift
  TwoHoSun/Screens/Home/MainView/MainView.swift
Labels: feat, 🎧 이
